# Generated by Django 2.2.2 on 2019-06-06 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('url', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=45)),
                ('location', models.CharField(max_length=45)),
                ('beneficiary', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('In-Progress', 'In-Progress')], max_length=45)),
                ('budget', models.DecimalField(decimal_places=3, max_digits=19)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/projects')),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('position', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('education', models.CharField(max_length=100)),
                ('payroll', models.DecimalField(decimal_places=3, max_digits=19)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/staff')),
            ],
            options={
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='Systems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('cost', models.DecimalField(decimal_places=3, max_digits=19)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/systems')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Company')),
            ],
            options={
                'verbose_name_plural': 'Systems',
            },
        ),
        migrations.CreateModel(
            name='SystemImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/systems')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Systems')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSystemJoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('Projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Projects')),
                ('Systems', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Systems')),
            ],
            options={
                'verbose_name_plural': 'PojectSystemJoint',
            },
        ),
        migrations.CreateModel(
            name='ProjectStaffJoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isLeader', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=45)),
                ('Projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Projects')),
                ('Staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Staff')),
            ],
            options={
                'verbose_name_plural': 'ProjectStaffJoint',
            },
        ),
        migrations.AddField(
            model_name='projects',
            name='PojectSystemJoint',
            field=models.ManyToManyField(related_name='projectSystems', through='core.ProjectSystemJoint', to='core.Systems'),
        ),
        migrations.AddField(
            model_name='projects',
            name='ProjectStaffJoint',
            field=models.ManyToManyField(related_name='projectStaff', through='core.ProjectStaffJoint', to='core.Staff'),
        ),
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/projects')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Projects')),
            ],
        ),
    ]
